apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app
        image: quiz-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  type: NodePort
  selector:
    app: quiz-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036
